logging:
  level:
    org:
      springframework:
        amqp: debug

spring:
  rabbitmq:
    addresses: centos:5672

  cloud:
    stream:
      function:
        definition: alertSource

      bindings:
        alertSource-out-0:
          destination: alerts
